hostname: nx-spine-2

underlay_interfaces:
  - name: Ethernet1/1
    address: 10.0.0.4/31
  - name: Ethernet1/2
    address: 10.0.0.6/31

bgp_rid:
  asn: 65000
  router_id: 100.64.60.2

isis:
  process: UNDERLAY
  net: 49.0001.0000.0000.0002.00

pim:
  rp_address: 100.64.61.1
  rp_local: 100.64.60.2
  rp_peer: 100.64.60.1