hostname: nx-leaf-4

underlay_interfaces:
  - name: Ethernet1/1
    address: 10.0.0.3/31
  - name: Ethernet1/2
    address: 10.0.0.7/31

bgp_rid:
  asn: 65000
  router_id: 100.64.60.4

isis:
  process: UNDERLAY
  net: 49.0001.0000.0000.0004.00

bgp_services:
  neighbor_as: 65012