hostname: nx-leaf-3

layer2:
  - interface: 1/1
    mtu: 9216
    vlan_id: 10
  - interface: 1/2
    mtu: 9216
    vlan_id: 10

vrfs_services:
  - vrf_name: &refvrf_ansiblevrf MYVRF
    vlan_name: *refvrf_ansiblevrf
    vlan_id: 10
    vni_id: 10

networks_services:
  - vrf_name: *refvrf_ansiblevrf
    vlan_name: MYVRF
    vlan_id: 10
    vni_id: 10
    addr: 10.1.1.1
    mask: 255.255.255.0
    mcast_grp: 225.10.10.10

bgp_rid:
  asn: 65000
  router_id: 3.3.3.3