features:
  - { feature: isis }
  - { feature: pim }
  - { feature: bgp }
  - { feature: nv overlay }
  - { feature: vn-segment-vlan-based }
  - { feature: interface-vlan }
  - { feature: netconf }
  - { feature: restconf }

bgp:
  asn: 65000
  neighbors:
    - neighbor: 100.64.60.1
      remote_as: 65000
      update_source: loopback0
    - neighbor: 100.64.60.2
      remote_as: 65000
      update_source: loopback0