features:
  - isis
  - pim
  - bgp
  - nv overlay
  - vn-segment-vlan-based
  - interface-vlan
  - netconf 
  - restconf 

bgp:
  asn: 65000
  neighbors:
    - neighbor: 100.64.60.1
      remote_as: 65000
      update_source: loopback0
    - neighbor: 100.64.60.2
      remote_as: 65000
      update_source: loopback0