features:
  - { feature: isis }
  - { feature: pim }
  - { feature: bgp }
  - { feature: nv overlay }
  - { feature: netconf }
  - { feature: restconf }

bgp:
  asn: 65000
  neighbors:
    - neighbor: 100.64.60.3
      remote_as: 65000
      update_source: loopback0
    - neighbor: 100.64.60.4
      remote_as: 65000
      update_source: loopback0