features:
  - isis
  - pim
  - bgp
  - nv overlay
  - netconf
  - restconf

bgp:
  asn: 65000
  neighbors:
    - neighbor: 100.64.60.3
      remote_as: 65000
      update_source: loopback0
    - neighbor: 100.64.60.4
      remote_as: 65000
      update_source: loopback0