---
- name: Configure interface as routed port (Layer 3)
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: layer3
        enabled: true
        description: "Underlay Interface with IS-IS" 
    state: merged
  loop: "{{ underlay_interfaces }}"

- name: Configure IPv4 addresses on routed ports
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        ipv4:
          - address: "{{ item.address }}"
    state: merged
  loop: "{{ underlay_interfaces }}"

- name: Configure Loopback addresses
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "Loopback0"
        ipv4:
          - address: "{{ bgp_rid.router_id }}/32"
    state: merged