---
- name: Configure global settings on Nexus-OS
  import_tasks: global.yml

- name: Configure NX-OS Features
  import_tasks: features.yml

- name: Configure Underlay Interfaces
  import_tasks: interfaces.yml

- name: Configure ISIS
  import_tasks: isis.yml

- name: Configure BGP
  import_tasks: bgp.yml

- name: Configure PIM
  import_tasks: pim.yml